name: Deploy Spring Boot to EC2 with PM2

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build the Application (skip tests)
        run: ./gradlew build -x test

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: build/libs/${{ secrets.JAR_NAME }}
          target: ~/app/

      - name: Restart Application using PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            mkdir -p ~/app
            cd ~/app

            # Stop existing app
            pm2 delete spring-app || true

            # Start or restart the JAR with PM2
            pm2 start java --name spring-app -- -jar ${{ secrets.JAR_NAME }}

            # Save PM2 process list
            pm2 save
